const AZURE_ONBOARD_LOCATION = 'eastus';
const AZURE_SQL_USERNAME = 'neova-test';
const AZURE_SQL_PASSWORD = 'Normalyze#12345';
const AZURE_SQL_REGION = 'westus';
const AZURE_RESOURCE_GROUP_NAME = 'neova-team';
const BLOB_DATA_STORE_API_TYPE = 'AZUREBLOB-CONTAINER';
const SQL_SERVER_DATA_STORE_API_TYPE = 'AZURESQL-SERVER';
const NORMALYZE_ACCOUNT_ID = 'f22fa846922f';

export {
    AZURE_ONBOARD_LOCATION,
    AZURE_SQL_USERNAME,
    AZURE_SQL_PASSWORD,
    AZURE_SQL_REGION,
    AZURE_RESOURCE_GROUP_NAME,
    BLOB_DATA_STORE_API_TYPE,
    SQL_SERVER_DATA_STORE_API_TYPE,
    NORMALYZE_ACCOUNT_ID
};
