// const AZURE_SUBSCRIPTION_ID = 'f22fa846-922f-4b91-a236-c866835dfe2a';
// const AZURE_TENANT_ID = 'cc896722-8466-4d25-820e-987cddbaf613';
// const AZURE_SERVICE_PRINCIPAL_ID = '7a4fc285-6864-4b1e-a082-919c2b2d5fb1';
// const AZURE_CLIENT_SECRET = '9ry8Q~50qy5tR_YL9bXtILgjs~FrXj.0pBvZScgG';
const AZURE_ONBOARD_LOCATION = 'eastus';
const AZURE_SQL_USERNAME = 'neova-test';
const AZURE_SQL_PASSWORD = 'Normalyze#12345';
const AZURE_SQL_REGION = 'westus';
const AZURE_RESOURCE_GROUP_NAME = 'neova-team';
const BLOB_DATA_STORE_API_TYPE = 'AZUREBLOB-CONTAINER';
const SQL_SERVER_DATA_STORE_API_TYPE = 'AZURESQL-SERVER';
const NORMALYZE_ACCOUNT_ID = 'f22fa846922f';

export {
    // AZURE_SUBSCRIPTION_ID,
    // AZURE_TENANT_ID,
    // AZURE_SERVICE_PRINCIPAL_ID,
    // AZURE_CLIENT_SECRET,
    AZURE_ONBOARD_LOCATION,
    AZURE_SQL_USERNAME,
    AZURE_SQL_PASSWORD,
    AZURE_SQL_REGION,
    AZURE_RESOURCE_GROUP_NAME,
    BLOB_DATA_STORE_API_TYPE,
    SQL_SERVER_DATA_STORE_API_TYPE,
    NORMALYZE_ACCOUNT_ID
};
